fix(checkservices): Added test for pacdiff
archlinux/contrib pull request #46
Opened 2021-09-17 23:14 UTC by mietinen

Added a simple test that set PACDIFF=0 if pacdiff is not installed.
Running pacdiff by default doesn't make sense as pacdiff is in the pacman-contrib package.

2021-09-18 13:45 UTC, jelly approved these changes

2021-12-01 10:03 UTC, jelly commented
Not, 100% a fan of it, as this hides an issue if you want to use pacdiff. So outputting a `warn skipping pacdiff as not installed` would be better.

2021-12-01 10:03 UTC, jelly requested changes
This hides the issue that pacdiff is not installed.

2022-06-06 21:48 UTC, Foxboron approved these changes

2022-06-06 21:48 UTC, Foxboron commented
Amended the commit and merged as https://github.com/archlinux/contrib/commit/3b20d07796cea924d7a2b4d0fd24cc28126cf3c1

Thanks :)

2022-06-06 21:48 UTC, closed without merging